[package]
name = "pdf-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.26"


[lib]
path = "src/lib.rs"


[[bin]]
name = "main"
path = "src/main.rs"
